/**
 * Vite plugin for dashboard plugin system.
 *
 * On dev start and build, scans ~/pi-dashboard/plugins/[star]/package.json for
 * `pi-dashboard-plugin` manifests and generates frontend/src/generated/plugin-registry.tsx
 * with named imports per claim (enables Vite tree-shaking of unused exports).
 *
 * During dev, watches manifest files for changes and regenerates on content change.
 */
import type { Plugin, ViteDevServer } from 'vite'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import type { PluginManifest, SlotId } from '../../shared/src/plugin-types.js'

const GENERATED_DIR = 'frontend/src/generated'
const GENERATED_FILE = 'plugin-registry.tsx'

function getGeneratedPath(repoRoot: string): string {
  return path.join(repoRoot, GENERATED_DIR, GENERATED_FILE)
}

interface PluginEntry {
  manifest: PluginManifest
  packageDir: string
  clientEntryPath: string
}

/** Scan plugins/ directory for valid pi-dashboard-plugin manifests. */
function discoverPlugins(repoRoot: string): PluginEntry[] {
  const pluginsDir = path.join(repoRoot, 'plugins')
  if (!fs.existsSync(pluginsDir)) return []

  const entries: PluginEntry[] = []
  for (const dir of fs.readdirSync(pluginsDir)) {
    const pkgPath = path.join(pluginsDir, dir, 'package.json')
    if (!fs.existsSync(pkgPath)) continue

    try {
      const raw = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'))
      const manifestField = raw['pi-dashboard-plugin']
      if (!manifestField) continue

      const manifest = manifestField as PluginManifest
      if (!manifest.id || !manifest.claims?.length) continue

      // Resolve client entry relative to the plugin directory
      const clientRelative = manifest.client ?? 'src/client.tsx'
      const clientAbsolute = path.join(pluginsDir, dir, clientRelative)
      if (!fs.existsSync(clientAbsolute)) {
        console.warn(`[dashboard-plugins] Plugin ${manifest.id}: client entry not found at ${clientAbsolute}`)
        continue
      }

      entries.push({
        manifest,
        packageDir: path.join(pluginsDir, dir),
        clientEntryPath: clientAbsolute,
      })
    } catch {
      // Skip malformed package.json
    }
  }

  return entries
}

const VALID_SLOTS: SlotId[] = ['tool-renderer', 'settings-section', 'command-route', 'sidebar-panel', 'status-bar', 'session-card-badge', 'content-header']

/** Generate the plugin-registry.tsx content with named imports per claim. */
function generateRegistryContent(entries: PluginEntry[]): string {
  const lines: string[] = [
    '// @ts-nocheck — Plugin files live outside frontend/ and may not resolve tsc types.',
    '// GENERATED — do not edit. Regenerated by dashboardPluginsPlugin on every build.',
    "import type { ClaimEntry, PluginManifest } from '@shared/plugin-types'",
    '',
  ]

  // Named imports per claim component
  for (const entry of entries) {
    const componentNames = [
      ...new Set(
        entry.manifest.claims
          .map(c => c.componentName)
          .filter((c): c is string => Boolean(c)),
      ),
    ]
    if (componentNames.length > 0) {
      lines.push(
        `import { ${componentNames.join(', ')} } from ${JSON.stringify(entry.clientEntryPath)}`,
      )
    }
  }

  lines.push('')
  lines.push('export interface RegistryEntry {')
  lines.push('  manifest: PluginManifest')
  lines.push('  claims: ClaimEntry[]')
  lines.push('}')
  lines.push('')
  lines.push('export const PLUGIN_REGISTRY: RegistryEntry[] = [')

  for (const entry of entries) {
    const { manifest } = entry
    lines.push('  {')
    lines.push(`    manifest: ${JSON.stringify(manifest, null, 4).split('\n').join('\n    ')},`)
    lines.push('    claims: [')
    for (const claim of manifest.claims) {
      if (!VALID_SLOTS.includes(claim.slot)) continue
      const parts: string[] = [
        `pluginId: ${JSON.stringify(manifest.id)}`,
        `priority: ${claim.priority ?? manifest.claims[0]?.priority ?? 1000}`,
        `slot: ${JSON.stringify(claim.slot)}`,
      ]
      if (claim.tab) parts.push(`tab: ${JSON.stringify(claim.tab)}`)
      if (claim.toolName) parts.push(`toolName: ${JSON.stringify(claim.toolName)}`)
      if (claim.command) parts.push(`command: ${JSON.stringify(claim.command)}`)
      if (claim.componentName) parts.push(`Component: ${claim.componentName}`)
      lines.push(`      { ${parts.join(', ')} },`)
    }
    lines.push('    ],')
    lines.push('  },')
  }

  lines.push(']')
  lines.push('')

  return lines.join('\n')
}

function hashContent(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex').slice(0, 16)
}

let lastHash = ''

function regenerate(repoRoot: string): { changed: boolean } {
  const entries = discoverPlugins(repoRoot)
  const content = generateRegistryContent(entries)
  const hash = hashContent(content)

  if (hash === lastHash) return { changed: false }

  const outPath = getGeneratedPath(repoRoot)
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, content, 'utf-8')
  lastHash = hash
  return { changed: true }
}

/**
 * Vite plugin for dashboard plugin registry generation.
 * @param repoRoot Absolute path to the repo root. Defaults to cwd parent (assumes called from frontend/).
 */
export function dashboardPluginsPlugin(repoRoot?: string): Plugin {
  const root = repoRoot ?? path.resolve(process.cwd(), '..')

  return {
    name: 'dashboard-plugins',
    enforce: 'pre',

    buildStart() {
      const { changed } = regenerate(root)
      if (changed) {
        console.info('[dashboard-plugins] Generated plugin-registry.tsx')
      }
    },

    configureServer(server: ViteDevServer) {
      const pluginsDir = path.join(root, 'plugins')
      if (!fs.existsSync(pluginsDir)) return

      // Watch all plugins/*/package.json for manifest changes
      const manifestPaths = fs
        .readdirSync(pluginsDir)
        .map(entry => path.join(pluginsDir, entry, 'package.json'))
        .filter(p => fs.existsSync(p))

      for (const mp of manifestPaths) {
        server.watcher.add(mp)
      }

      server.watcher.on('change', (filePath: string) => {
        if (!manifestPaths.includes(filePath)) return
        try {
          const raw = JSON.parse(fs.readFileSync(filePath, 'utf-8'))
          if (!raw['pi-dashboard-plugin']) return
        } catch {
          return
        }

        const { changed } = regenerate(root)
        if (changed) {
          console.info('[dashboard-plugins] Manifest changed, regenerated plugin-registry.tsx')
          const generatedPath = getGeneratedPath(root)
          const mod = server.moduleGraph.getModuleById(generatedPath)
          if (mod) {
            server.moduleGraph.invalidateModule(mod)
            server.ws.send({ type: 'full-reload' })
          }
        }
      })
    },
  }
}
